# Generated by Django 5.2.17 on 2026-09-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('issuer', models.CharField(max_length=255)),
                ('issued_at', models.DateField()),
                ('credential_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
