# Generated by Django 5.2.17 on 2026-09-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification',
            new_name='Achievement',
        ),
    ]
